apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-board
  namespace: stage
spec:
  ingressClassName: nginx
  rules:
  - host: "community.abyssworks.blog"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: community-board
            port:
              number: 80
