apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: board-prod
commonLabels:
  project: board
  environment: prod
resources:
  - namespace.yaml
  - board.yaml
  - board-svc.yaml
  - postgres.yaml
  - ingress.yaml
images:
- name: board
  newTag: prod
