apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: board-prod
  namespace: argocd
spec:
  destination:
    namespace: board-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/abyss-works/board
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
